### ISSUE TITLE
ecu registration fails with error 404

### ISSUE THREAD

**Issue by msatpathy26** [advancedtelematic/director#206]
While starting aktualizr in device provision mode it shows the below error.

root@raspberrypi4:/var/sota# aktualizr --loglevel 0
Aktualizr version 2020.7-127-g4169157a1 starting
Reading config: "/usr/lib/sota/conf.d/20-sota-device-cred.toml"
Reading config: "/usr/lib/sota/conf.d/30-rollback.toml"
Reading config: "/etc/sota/conf.d/40-hardware-id.toml"
Final configuration that will be used: 
[logger]
loglevel = 0

[p11]
module = ""
pass = ""
uptane_key_id = ""
tls_ca_id = ""
tls_pkey_id = ""
tls_clientcert_id = ""

[tls]
server = "https://ota-ce.uptanedemo.com:8443"
server_url_path = "/var/sota/import/gateway.url"
ca_source = "file"
pkey_source = "file"
cert_source = "file"

[provision]
server = "https://ota-ce.uptanedemo.com:8443"
p12_password = ""
expiry_days = "36000"
provision_path = ""
device_id = ""
primary_ecu_serial = "e7963201-e012-4d3c-b9c9-fca505ad8091"
primary_ecu_hardware_id = "raspberrypi4"
ecu_registration_endpoint = "https://ota-ce.uptanedemo.com:8443/director/api/v1/raspberrypi4/:e7963201-e012-4d3c-b9c9-fca505ad8091/ecus"
mode = "DeviceCred"

[uptane]
polling_sec = 10
director_server = "https://ota-ce.uptanedemo.com:8443/director"
repo_server = "https://ota-ce.uptanedemo.com:8443/repo"
key_source = "file"
key_type = "RSA2048"
force_install_completion = false
secondary_config_file = ""
secondary_preinstall_wait_sec = 600

[pacman]
type = "ostree"
os = ""
sysroot = ""
ostree_server = "https://ota-ce.uptanedemo.com:8443/treehub"
images_path = "/var/sota/images"
packages_file = "/usr/package.manifest"
fake_need_reboot = false

[storage]
type = "sqlite"
path = "/var/sota"
sqldb_path = "sql.db"
uptane_metadata_path = "metadata"
uptane_private_key_path = "ecukey.der"
uptane_public_key_path = "ecukey.pub"
tls_cacert_path = "root.crt"
tls_pkey_path = "pkey.pem"
tls_clientcert_path = "client.pem"

[import]
base_path = "/var/sota/import"
uptane_private_key_path = ""
uptane_public_key_path = ""
tls_cacert_path = "root.crt"
tls_pkey_path = "pkey.pem"
tls_clientcert_path = "client.pem"

[telemetry]
report_network = true
report_config = true

[bootloader]
rollback_mode = "uboot_masked"
reboot_sentinel_dir = "/var/run/aktualizr-session"
reboot_sentinel_name = "need_reboot"
reboot_command = "/sbin/reboot"

Current directory: /var/sota
Use existing SQL storage: "/var/sota/sql.db"
meta with role root in repo director not present in db
meta with role root in repo image not present in db
No serial found in database for this ECU, defaulting to empty serial
Checking if device is provisioned...
post request body:{
        "ecus" : 
        [
                {
                        "clientKey" : 
                        {
                                "keytype" : "RSA",
                                "keyval" : 
                                {
                                        "public" : "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1lP/49jYvsDxGFQ0vdqd\nsZJS"
                                }
                        },
                        "ecu_serial" : "e7963201-e012-4d3c-b9c9-fca505ad8091",
                        "hardware_identifier" : "raspberrypi4"
                }
        ],
        "primary_ecu_serial" : "e7963201-e012-4d3c-b9c9-fca505ad8091"
}
*   Trying 35.232.82.33:8443...
* Connected to ota-ce.uptanedemo.com (35.232.82.33) port 8443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /tmp/aktualizr-6ec8-af15-c45c-020e/8282-18d6-tls-ca
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=ota-gateway
*  start date: Aug 30 20:40:46 2020 GMT
*  expire date: Aug 28 20:40:46 2030 GMT
*  subjectAltName: host "ota-ce.uptanedemo.com" matched cert's "ota-ce.uptanedemo.com"
*  issuer: CN=ota-server-CA
*  SSL certificate verify ok.
> POST /director/api/v1/raspberrypi4/:e7963201-e012-4d3c-b9c9-fca505ad8091/ecus HTTP/1.1
Host: ota-ce.uptanedemo.com:8443
User-Agent: Aktualizr/2020.7-127-g4169157a1
Accept: */*
Content-Type: application/json
Content-Length: 674

* upload completely sent off: 674 out of 674 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Server: nginx/1.13.7
< Date: Sun, 30 Aug 2020 22:24:17 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 42
< Connection: keep-alive
< x-ats-version: director/0.2.0-27-gcd592e6
< 
* Connection #0 to host ota-ce.uptanedemo.com left intact
response http code: 404
response: The requested resource could not be found.
Flushing report queue
Initializer error: Server error: Error registering device: 404 The requested resource could not be found.

Any idea what's going wrong ?

**Comment by houcros** [comment]
At first sight, director's version is _very_ old. I could recommend to use latest versions of the services, see https://github.com/advancedtelematic/ota-community-edition/pull/103.

**Comment by msatpathy26** [comment]
@houcros This error was gone after updating the Director's version. Thanks for the pointer.
